### ISSUE TITLE
MarkdownPreview doesn't work in OS X

### ISSUE THREAD

**Issue by c4pt0r** [iamcco/markdown-preview.vim#1]
I created an alias in my zshrc:
alias google-chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
but it doesn't work.

**Comment by 19000** [comment]
AFAIK aliases only work in shell command line. Unlike environment variables, they are not passed to subprocesses like vim. So vim fail to acquire the path.

The two commands below both work on my machine. Have a try!
```vim
let g:mkdp_path_to_chrome = "open -a Google\\ Chrome"
```
```vim
let g:mkdp_path_to_chrome = "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome"
```

**Comment by c4pt0r** [comment]
cool, it works.
