### ISSUE TITLE
Support for Github Flavored Markdown rendering

### ISSUE THREAD

**Issue by tnguyen14** [iamcco/markdown-preview.vim#13]
Can this plugin support Github Flavored Markdown? 

Also supporting for rendering the markdown in the Github styles would be great as well.

**Comment by iamcco** [comment]
This plugin support Github Flavored Markdown by default.  I will create an Github like styles when i have time.

**Comment by tnguyen14** [comment]
Hmm.. When I tried the following

```
- [ ] todo
- [ ] todo2
```

They were not rendered as check lists for me.

**Comment by iamcco** [comment]
the task list is not support yet :(

**Comment by iamcco** [comment]
The latest update is support the task list and has Github like styles. Closed!

**Comment by tnguyen14** [comment]
Your support is amazing!! Thank you so much!!
