### ISSUE TITLE
我默认使用 safari，应该如何修改

### ISSUE THREAD

**Issue by shenwusw** [iamcco/markdown-preview.vim#15]
python v2x支持，输入 command 后没有任何反应。。我猜是因为你的插件默认使用 chrome，我使用 safari
我是直接在.vimrc 里面加了let g:mkdp_path_to_chrome = "/Applications/Safari.app"
但是safari没有反应，是应该在 bundle 里 markdown-preview 里面找文件修改吗？

**Comment by iamcco** [comment]
不需要到插件里面改，可以试下这个
`let g:mkdp_path_to_chrome = "open -a Safari"`

具体mac 下设置看这里[issue1](https://github.com/iamcco/markdown-preview.vim/issues/1)

**Comment by shenwusw** [comment]
成功了！！
*快感动哭了*～～～～～

**Comment by iamcco** [comment]
:smile:
