### ISSUE TITLE
Windows下网页无法预览

### ISSUE THREAD

**Issue by ikarixiao** [iamcco/markdown-preview.vim#16]
你好！感谢你发布了这么神奇的插件。在使用插件中出现了无法预览的问题。
显示如下：
![image 2](https://cloud.githubusercontent.com/assets/4947505/15047800/30c5f0c8-1319-11e6-9e2d-04553a7c3120.png)
已将Chrome添加进Path环境变量。Windows 10 X64系统，64位Python 2.7，Vim 7.4。
请问应该如何解决？
非常感谢！

又另：
直接运行Python server.py没有反应。

**Comment by iamcco** [comment]
@ikarixiao 能贴一下你的关于这个插件的配置吗？

1. 确认插件安装并且配置正确
2. 打开一个 markdown 文件
3. echo g:mkdp_server_started

看下第3步显示的是0还是1

**Comment by ikarixiao** [comment]
第3步显示是0。

**Comment by iamcco** [comment]
@ikarixiao 把你的配置贴一下，关于这个插件的

**Comment by ikarixiao** [comment]
不知道为什么图贴不上来。

Plugin 'iamcco/markdown-preview.vim'

let g:mkdp_path_to_chrome = "chrome"
    " 设置 chrome 浏览器的路径（或是启动 chrome（或其他现代浏览器）的命令）

    let g:mkdp_auto_start = 0
    " 设置为 1 可以在打开 markdown 文件的时候自动打开浏览器预览，只在打开
    " markdown 文件的时候打开一次

    let g:mkdp_auto_open = 0
    " 设置为 1 在编辑 markdown 的时候检查预览窗口是否已经打开，否则自动打开预
    " 览窗口

    let g:mkdp_auto_close = 1
    " 在切换 buffer 的时候自动关闭预览窗口，设置为 0 则在切换 buffer 的时候不
    " 自动关闭预览窗口

    let g:mkdp_refresh_slow = 0
    " 设置为 1 则只有在保存文件，或退出插入模式的时候更新预览，默认为 0，实时
    " 更新预览

**Comment by iamcco** [comment]
@ikarixiao 现在打开一个markdown文件，:MarkdownPreview看看报的什么错，然后:messages，把所有错误信息贴上来，我要看到所有的报错才能定位到问题

**Comment by ikarixiao** [comment]
![](https://img3.doubanio.com/view/status/median/public/79ce17501ad59ae.jpg)
![](https://img1.doubanio.com/view/status/median/public/c0073d2327e6347.jpg)
显示的错误大致如此。

**Comment by iamcco** [comment]
呃，上面提示了需要vim支持python，你:echo has('python') 或 :echo has('python3') 应该显示0，这个可能是没装Python，或者vim不支持Python，或者你本地的python和vim的位数对不上，比如python是64位的，vim是32位的，或者反过来

**Comment by ikarixiao** [comment]
呃，还真是。。。：echo has（‘python’）确实是0。。。我确实装的是32位Vim，我大概知道怎么解决了。。。
