### ISSUE TITLE
Install with Vundle

### ISSUE THREAD

**Issue by tnguyen14** [iamcco/markdown-preview.vim#2]
Can this plugin be installed with Vundle? I tried, but it didn't seem to work..

**Comment by iamcco** [comment]
@tnguyen14 I install this plugin with Vundle. Maybe you can check if the **g:mkdp_path_chrome** that you set can open the browser

**Comment by iamcco** [comment]
Closed!

**Comment by tnguyen14** [comment]
It is set to `google-chrome`. Do you expect that to be an available executable in bash to open the browser?

**Comment by tnguyen14** [comment]
Also, sorry for not responding to the original reply. I must've missed it somehow.

**Comment by iamcco** [comment]
the `google-chrome` is an environment variables that can open the browser.
if you are using OS X you can see this issue [#1](https://github.com/iamcco/markdown-preview.vim/issues/1)

BTW, feel free to let me know what works / doesn't work for you!

**Comment by iamcco** [comment]
@tnguyen14 you can set the `g:mkdp_path_chrome` in you vimrc

example:
```viml
let g:mkdp_path_chrome = "firefox"
```
use the firefox to preview the markdown

**Comment by tnguyen14** [comment]
Yup, either of the solutions mentioned in #1 works. Perhaps the readme could be updated with that info for OS X users?

**Comment by iamcco** [comment]
Good idea,  i will update the readme
