### ISSUE TITLE
不能自动关闭firefox的标签

### ISSUE THREAD

**Issue by mah0ne** [iamcco/markdown-preview.vim#21]
设置 默认的浏览器 为firefox时, 能自动打开, 但是关闭不了,
使用google-chrome一切正常.

**Comment by iamcco** [comment]
@mah0ne 这个是因为火狐浏览器不支持控制关闭页面。不知道有什么方法

**Comment by mah0ne** [comment]
@iamcco  找到这个, 不知道这几个是不是有什么区别, 对这方面还不太懂
http://stackoverflow.com/questions/165779/are-the-put-delete-head-etc-methods-available-in-most-web-browsers

**Comment by iamcco** [comment]
@mah0ne 关闭页面的方法是调用 `window.close()` 火狐禁用了非js脚本通过 `window.open()` 之外打开的页面关闭的功能。就是说只有通过调用 `window.open()` 打开的页面，调用 `window.close()` 还能关闭。目前我还没找到其他方法。

**Comment by mah0ne** [comment]
@iamcco   测试可行, 打开firefox 
`about:config`
搜索找到
`dom.allow_scripts_to_close_windows` 
将`value` 设置成 `true`, 看看能不能加进使用文档里面

**Comment by iamcco** [comment]
@mah0ne 多谢，已经在文档和README更新
