### ISSUE TITLE
中文标题的问题

### ISSUE THREAD

**Issue by Uyiim** [iamcco/markdown-preview.vim#24]
比如
 ### 测试
转换成浏览器html会变成
 \<h3 id="-">测试\</h3>
id属性会变成了"-"，写跳转的时候就是会出问题了

**Comment by iamcco** [comment]
已经修复，由于使用的markedjs进行的markdown转换，在处理标题的 ID属性的时候，他所有的非 `\w`转为了横杠，所以就出现了问题，现在的做法是将所有的空字符转为横杠，比如

```
### 测 试
转为
<h3 id="测-试">测 试</h3>
```
酱紫行吗
