### ISSUE TITLE
使用Vundle安装之后，完全没有启动

### ISSUE THREAD

**Issue by jiahony** [iamcco/markdown-preview.vim#25]
你好！
我是一个Windows平台的用户，今天花了一天时间在网上查询可能在Win平台能够实时预览pandoc's markdown的插件，发现几乎无一另外，全只支持Unix系统，直到发现这款插件。
在使用Vundle安装插件后，发现与没有安装完全一样，无法使用MarkdownPreview，相关命令就没有出现在Commandline的自动补全菜单里。双击启动server.py则一闪而过。请问为何？
感谢开发这款插件，谢谢！

**Comment by iamcco** [comment]
不知道你是否安装正确，如果正确安装，在打开markdown文件后是会有MarkdownPreview命令的，还有这个插件需要你的gvim支持Python特性，并且安装有可用的python环境。

如果方便的话，可以把这个插件的相关配置贴出来，还有就是使用的gvim版本，支持的特性这些，还有python版本，是否可用这些贴出来，我好方便排插问题。

**Comment by jiahony** [comment]
感谢如此迅速的回复。

- 以下是我的Vim版本信息：  
`VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul 17 2016 19:50:24)
MS-Windows 32-bit GUI version
Included patches: 1-2066  
    Huge version with GUI.  Features included (+) or not (-):
+acl                +eval               +mouseshape         +tag_binary
+arabic             +ex_extra           +multi_byte_ime/dyn +tag_old_static
+autocmd            +extra_search       +multi_lang         -tag_any_white
+balloon_eval       +farsi              -mzscheme           -tcl
+browse             +file_in_path       +netbeans_intg      -termguicolors
++builtin_terms     +find_in_path       +num64              -tgetent
+byte_offset        +float              -ole                -termresponse
+channel            +folding            +packages           +textobjects
+cindent            -footer             +path_extra         +timers
+clientserver       +gettext/dyn        +perl/dyn           +title
+clipboard          -hangul_input       +persistent_undo    +toolbar
+cmdline_compl      +iconv/dyn          -postscript         +user_commands
+cmdline_hist       +insert_expand      +printer            +vertsplit
+cmdline_info       +job                +profile            +virtualedit
+comments           +jumplist           +python/dyn         +visual
+conceal            +keymap             +python3/dyn        +visualextra
+cryptv             +langmap            +quickfix           +viminfo
+cscope             +libcall            +reltime            +vreplace
+cursorbind         +linebreak          +rightleft          +wildignore
+cursorshape        +lispindent         +ruby/dyn           +wildmenu
+dialog_con_gui     +listcmds           +scrollbind         +windows
+diff               +localmap           +signs              +writebackup
+digraphs           +lua/dyn            +smartindent        -xfontset
-directx            +menu               +startuptime        -xim
-dnd                +mksession          +statusline         -xterm_save
-ebcdic             +modify_fname       -sun_workshop       -xpm_w32
+emacs_tags         +mouse              +syntax             
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
  system gvimrc file: "$VIM\gvimrc"
    user gvimrc file: "$HOME\_gvimrc"
2nd user gvimrc file: "$HOME\vimfiles\gvimrc"
3rd user gvimrc file: "$VIM\_gvimrc"
    system menu file: "$VIMRUNTIME\menu.vim"
Compilation: i686-pc-mingw32-gcc -Iproto -DWIN32 -DWINVER=0x0501 
-D_WIN32_WINNT=0x0501 -DHAVE_PATHDEF -DFEAT_HUGE -DHAVE_STDINT_H 
-DHAVE_GETTEXT -DHAVE_LOCALE_H -DDYNAMIC_GETTEXT -DFEAT_CSCOPE 
-DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL -DFEAT_GUI_W32 
-DFEAT_CLIPBOARD -DFEAT_MBYTE -DFEAT_MBYTE_IME -DDYNAMIC_IME 
-DDYNAMIC_ICONV -pipe -march=i686 -Wall -I/cygdrive/c/strawberry/perl/lib/Cor
e -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS 
-DDYNAMIC_PERL -DDYNAMIC_PERL_DLL="perl518.dll" -I/cygdrive/c/PROGRA~2/
Lua/5.1/include -I/cygdrive/c/PROGRA~2/Lua/5.1 -DFEAT_LUA -DDYNAMIC_LUA 
-DDYNAMIC_LUA_DLL="lua51.dll" -DFEAT_RUBY -I /cygdrive/c/Ruby22/lib/ruby/2.
2.0/i386-mingw32 -I /cygdrive/c/Ruby22/include/ruby-2.2.0 -I /cygdrive/c/Ruby22
/include/ruby-2.2.0/i386-mingw32 -DDYNAMIC_RUBY -DDYNAMIC_RUBY_DLL="m
svcrt-ruby220.dll" -DDYNAMIC_RUBY_VER=22 -DFEAT_PYTHON 
-DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL="python27.dll" 
-DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL="python33
.dll" -O3 -fomit-frame-pointer -freg-struct-return -s
Linking: i686-pc-mingw32-gcc -Iproto -DWIN32 -DWINVER=0x0501 
-D_WIN32_WINNT=0x0501 -DHAVE_PATHDEF -DFEAT_HUGE -DHAVE_STDINT_H 
-DHAVE_GETTEXT -DHAVE_LOCALE_H -DDYNAMIC_GETTEXT -DFEAT_CSCOPE 
-DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL -DFEAT_GUI_W32 
-DFEAT_CLIPBOARD -DFEAT_MBYTE -DFEAT_MBYTE_IME -DDYNAMIC_IME 
-DDYNAMIC_ICONV -pipe -march=i686 -Wall -I/cygdrive/c/strawberry/perl/lib/Cor
e -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS 
-DDYNAMIC_PERL -DDYNAMIC_PERL_DLL="perl518.dll" -I/cygdrive/c/PROGRA~2/
Lua/5.1/include -I/cygdrive/c/PROGRA~2/Lua/5.1 -DFEAT_LUA -DDYNAMIC_LUA 
-DDYNAMIC_LUA_DLL="lua51.dll" -DFEAT_RUBY -I /cygdrive/c/Ruby22/lib/ruby/2.
2.0/i386-mingw32 -I /cygdrive/c/Ruby22/include/ruby-2.2.0 -I /cygdrive/c/Ruby22
/include/ruby-2.2.0/i386-mingw32 -DDYNAMIC_RUBY -DDYNAMIC_RUBY_DLL="m
svcrt-ruby220.dll" -DDYNAMIC_RUBY_VER=22 -DFEAT_PYTHON 
-DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL="python27.dll" 
-DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL="python33
.dll" -O3 -fomit-frame-pointer -freg-struct-return -s -mwindows -o gvim.exe 
-lkernel32 -luser32 -lgdi32 -ladvapi32 -lcomdlg32 -lcomctl32 -lversion -lwsock32 
-lole32 -luuid`   
- 在命令行中使用命令`echo has('python')`显示为`1`，使用`echo has('python3')`显示为`0`。
- 在系统`path`变量中有python27的路径:`c:\Python27\`和`c:\Python27\Scripts\`
- 在命令行中运行`python`显示：  
`Python 2.7.12 (v2.7.12:d33e0cf91556...) [MSC v. 1500 32 bit (Intel)] on win32`
- 在`~/_vimrc`中添加的配置设置为：  
`let g:mkdp_path_to_chrome = "c:/Program\ Files\ (x86)/Google/Chrome/Application/chrome.exe"`  
`let g:mkdp_auto_close = 0`  
`nmap <silent> <F8> <Plug>MarkdownPreview        " 普通模式`  
`imap <silent> <F8> <Plug>MarkdownPreview        " 插入模式`  
`nmap <silent> <F9> <Plug>StopMarkdownPreview    " 普通模式`  
`imap <silent> <F9> <Plug>StopMarkdownPreview    " 插入模式`  
- 编辑文件的后缀为`.md`
- 目前已经安装的插件有：  
```
Plugin 'scrooloose/nerdtree'  
Plugin 'scrooloose/syntastic'  
Plugin 'vim-airline/vim-airline'  
Plugin 'vim-airline/vim-airline-themes'  
Plugin 'konfekt/fastfold'  
Plugin 'SirVer/ultisnips'  
Plugin 'Shougo/neocomplete'  
Bundle 'honza/vim-snippets'  
Plugin 'tpope/vim-surround'  
Plugin 'lervag/vimtex'  
Plugin 'junegunn/vim-easy-align'  
Plugin 'ctrlpvim/ctrlp.vim'  
Plugin 'tpope/vim-commentary'  
Plugin 'luochen1990/rainbow'  
Plugin 'easymotion/vim-easymotion'  
Plugin 'vim-pandoc/vim-pandoc'  
Plugin 'vim-pandoc/vim-pandoc-syntax'  
Plugin 'vim-pandoc/vim-pandoc-after'  
Plugin 'vim-pandoc/vim-rmarkdown'  
Plugin 'jalvesaq/Nvim-R'  
Plugin 'dhruvasagar/vim-table-mode'  
Plugin 'iamcco/markdown-preview.vim'
```

**Comment by iamcco** [comment]
修改了一点，更新插件试试

**Comment by iamcco** [comment]
```
let g:mkdp_path_to_chrome = 'c:/Program\ Files\ (x86)/Google/Chrome/Application/chrome.exe'
```
设置这个路径，如果路径中有空格的话，要使用单引号

还有，测试一下 `:py print 'hello world'` 看看输出什么

**Comment by jiahony** [comment]
刚刚更新的插件，并且将Chrome的路径修改为了用单引号包裹：
`'c:/Program\ Files\ (x86)/Google/Chrome/Application/chrome.ex''e`。

可是更新完之后仍然不能使用……仍然没有MarkdownPreview命令。

在gVim的命令行里通过`py print 'hello world'`可能正常在命令行里输出`hello world`。

现在手动双击运行`server.py`不会一闪而过，而是停留在一个全黑的空白界面，没有任何输出。
如果cd到`server.py`所在目录，运行`py server.py`则显示`Unable to create process using '/bin/usr env python server.py'`

**Comment by iamcco** [comment]
不用单引号，因为你路径空格已经转义了，改成双引号，然后打开md文件输入MarkdownPreview有什么报错么？或者有什么提示？

**Comment by jiahony** [comment]
已经修改成了双引号。打开md文件输入`:MarkdownPreview`后显示`E492: Not an editor command: MarkdownPreview`。给我的感觉插件并没有被载入。

**Comment by iamcco** [comment]
如果装好了的话，应该是有这个命令的，你vim启动的时候也没有报错或提示之类的？其他的插件也是这样安装的么？

**Comment by jiahony** [comment]
我是使用`Vundle`安装的，命令为`Plugin 'iamcco/markdown-preview.vim'`。其他插件也是使用这种方式来安装的。在启动Vim时没有任何错误提示或者报错。
有没有可能手动安装这个插件，然后让我来手动启动它？这样来排查一下是不是安装的问题。

**Comment by iamcco** [comment]
我用win7测试了一遍，用的Vundle安装发现没有问题。手动安装就是吧`markdown-preview.vim`文件夹里面的文件复制到vim安装目录对应的目录就行了。

比如：markdown-preview.vim一共有autoload,doc,plugin这三个是必要的文件，把autoload里面的所有文件复制到vim74/autoload/，把doc里面的文件复制到vim74/doc/，把plugin里面的文件复制到vim74/plugin/

这样手动安装就完成了，不过不建议这样安装，不好管理

**Comment by jiahony** [comment]
我放弃了。即使按照上述方法想手动启动这个插件，依旧不成功。

谢谢你的帮助。

**Comment by iamcco** [comment]
好吧，其实我觉得还是可以在试试的，这样的话先关闭了
