### ISSUE TITLE
Stay in Vim after MarkdownPreview command

### ISSUE THREAD

**Issue by tamlok** [iamcco/markdown-preview.vim#27]
Can I stay in Vim after opening MarkdownPreview webpage? Thanks very much!

**Comment by iamcco** [comment]
It can't stay the vim window on top. But if you use gvim on windows maybe you can use the `gvimfullscreen` dll to do it for you.

1. `gvimfullscreen` dll is [here](https://github.com/iamcco/vimrc.backup/tree/winbin/bin)
2. config for `gvimfullscreen` dll is [here](https://github.com/iamcco/vimrc.backup/blob/master/vimrc#L310-L318)

> the `gvimfullscreen` dll file must in the path of the environment

**Comment by tamlok** [comment]
OK, thanks very much!
