### ISSUE TITLE
Any plan for TOC support?

### ISSUE THREAD

**Issue by tamlok** [iamcco/markdown-preview.vim#28]
Any plan for [TOC] support?
Great work in Windows! Thanks very  much!

**Comment by iamcco** [comment]
At this time there is no plan for new feature such as [TOC].

**Comment by wsdjeg** [comment]
@tamlok @iamcco If you need toc, I think you can use https://github.com/mzlogin/vim-markdown-toc

This is a plugin for generate toc. I use it together with this plugin.
