### ISSUE TITLE
Proper page title when previewing in Chrome

### ISSUE THREAD

**Issue by tamlok** [iamcco/markdown-preview.vim#29]
I set auto_close to false, so I will have multiple preview pages open in Chrome. However all of their titles are the same "Markdown Preview", which confuse me when I want to view a certain page.
Can we make the preview page title identical to the corresponding name of the markdown file?
Thanks very much!

**Comment by iamcco** [comment]
I can fix it but have to wait until the weekend.

**Comment by iamcco** [comment]
fix, update and have a try.

**Comment by tamlok** [comment]
@iamcco Thanks very much!
