### ISSUE TITLE
无法打开预览

### ISSUE THREAD

**Issue by maonx** [iamcco/markdown-preview.vim#3]
设置好浏览器chrome后运行成功浏览器无法显示。
启动好像不太稳定，老是失败，弹出如下提示。
![image](https://cloud.githubusercontent.com/assets/272345/10069014/d2e0f9c8-62db-11e5-8d37-fb50a5f637ad.png)
帮忙看下是什么问题，win7 64位系统

**Comment by iamcco** [comment]
@maonx 这个错误应该是`g:mkdp_path_chrome`没有设置对，这个变量应该要设置为chrome浏览器路径，或者是能够打开chrome的命令。   
比如我的chrome路径设置是  
` let g:mkdp_path_to_chrome = "c:/Program\ Files\ (x86)/Google/Chrome/Application/chrome.exe"`   
 注意路径中的空格

**Comment by maonx** [comment]
我直接设置的是你的默认值，把Google的链接改名为你的默认值，并且设置Google运行目录加到Path，可以运行打开浏览器网页，但显示网页无法加载，有时候就显示出错，不太稳定。

**Comment by iamcco** [comment]
@maonx 能自动打开浏览器证明设置应该没有错的，显示网页无法加载，应该是后台server没启动，你电脑安装有python2或python3吗？

**Comment by maonx** [comment]
有Python3呢 因为vim插件也需要python3的 ，python3 要设置吗？ 或添加Path？

**Comment by iamcco** [comment]
@maonx 需要添加Path，因为在windows下面server是通过 `python server.py` 这种方式启动的

**Comment by maonx** [comment]
好的，谢谢明天去公司在试用下，在家是OSX

**Comment by maonx** [comment]
还是无法显示，在命令行已经能运行python命令，py3.4.2版本
![image](https://cloud.githubusercontent.com/assets/272345/10092520/e04f0a20-6379-11e5-9306-f8728b73f983.png)

**Comment by iamcco** [comment]
@maonx 好诡异。。。
