### ISSUE TITLE
How to insert a local image?

### ISSUE THREAD

**Issue by tamlok** [iamcco/markdown-preview.vim#30]
I try to insert a local image like this:
```
![image](d:/image/001.jpg)
```
But the preview page shows nothing about the image.

Could I insert a local image using relative path to the md file like this:
```
# example.md
![image](image/001.jpg)
```
Notice that "image" is at the same level with the "example.md". That would make the images management more convenient.

Thanks very much!

**Comment by iamcco** [comment]
fix now , update and have a try

**Comment by iamcco** [comment]
you can insert an image with absolute path and relative path.

example:
![image](c:\image.jpg)
![image](image/image.jpg)
![image](../image.jpg)

if something wrong and it's an issue

**Comment by tamlok** [comment]
Perfect! Now `![image](image/image.jpg)` works.
However, there is still something wrong with the list:
```
1. abc
2. abcd
3. ajdjd
  ![image](images/001.jpg)

![image](images/002.jpg)
```
`002.jpg` is displayed correctly, while `001.jpg` is displayed as a broken image.

Thanks!

**Comment by iamcco** [comment]
small fix, it will be OK now

**Comment by tamlok** [comment]
Thank you very much for your quick response!
