### ISSUE TITLE
调用:MarkdownPreview报错

### ISSUE THREAD

**Issue by bili** [iamcco/markdown-preview.vim#33]
![qq 20161214110729](https://cloud.githubusercontent.com/assets/449648/21168285/c9944a92-c1ed-11e6-832d-a8aa5636106f.png)

**Comment by bili** [comment]
我是用vundle方式安装，一开始提示没有python（但通过vim --version发现其实是支持的），后来再每次执行该命令，都报这个错。

**Comment by iamcco** [comment]
电脑上有安装python吗？看看 `:py print 'test'` 输出什么

**Comment by bili** [comment]
问题解决了。
按你说的输入命令后报错。
![qq 20161214130423](https://cloud.githubusercontent.com/assets/449648/21170327/28ebfbd2-c1ff-11e6-8d02-e23b3bbd9c10.png)
python确实是有安装的，不过包括系统和python，我都是64位的，估计是vim支持不太好，改成32位的python2.7后，功能正常了。
