### ISSUE TITLE
Pathogen support

### ISSUE THREAD

**Issue by paul-mesnilgrente** [iamcco/markdown-preview.vim#48]
Hi your work seems interesting. But I am using pathogen as package manager for vim and I prefer to not use another one.

I have tried but with no success.

Is it possible to make it work with pathogen?

**Comment by wz520** [comment]
Hi,
I am using this plugin with pathogen for more than one year and it works fine all the time.

If you cannot use the MarkdownPreview command after you open a file, maybe the name of that file does not match the pattern `*.{md,mkd,markdown,mdown,mkdn,mdwn}`. By default, the MarkdownPreview command can be only used for the files matching this pattern.

If you want the command to be valid with all files, try to add `let g:mkdp_command_for_global = 1` in your .vimrc file.

**Comment by iamcco** [comment]
close. feel free to reopen if you have any question
