### ISSUE TITLE
执行 MarkdownPreview 命令错误

### ISSUE THREAD

**Issue by Wuxiangdong** [iamcco/markdown-preview.vim#49]
### 截图
![screenshot_20170811_214909](https://user-images.githubusercontent.com/7942339/29215868-4a949918-7edf-11e7-8d4f-44b1b77614b7.png)
### vim配置
```
Plug 'iamcco/mathjax-support-for-mkdp'
Plug 'iamcco/markdown-preview.vim'


let g:mkdp_path_to_chrome = 'firefox'
nmap <silent> <F7> <Plug>MarkdownPreview
imap <silent> <F7> <Plug>MarkdownPreview
```
### 环境
ArchLinux vim 8.0

### 补充
用了root运行vim还是错误，似乎不是权限问题   
用了一个新的vim还是错误，似乎不是其他插件冲突

**Comment by Wuxiangdong** [comment]
SpaceVim的[#438](https://github.com/SpaceVim/SpaceVim/issues/438)也提到了这个问题
这个Issue就放这里吧,我先用别的插件代替.

**Comment by Wuxiangdong** [comment]
最近发现只要把`autoload/mkdp.vim`下的
`call system("python " . s:path_to_server . " " . g:mkdp_port . " &>/dev/null &")`
和
`call system(g:mkdp_path_to_chrome . " \"http://127.0.0.1:" . g:mkdp_port . "/markdown/" . g:mkdp_prefix . bufnr('%') . '?' . g:mkdp_cwd . "\" &>/dev/null &")`
中第一个`&`删掉，即改成
`call system("python " . s:path_to_server . " " . g:mkdp_port . " >/dev/null &")`
`call system(g:mkdp_path_to_chrome . " \"http://127.0.0.1:" . g:mkdp_port . "/markdown/" . g:mkdp_prefix . bufnr('%') . '?' . g:mkdp_cwd . "\" >/dev/null &")`
就不会出现错误了

**Comment by iamcco** [comment]
很奇怪，把 `&>/dev/null &` 换成 `>/dev/null 2>&1 &` 试下是否 OK

**Comment by Wuxiangdong** [comment]
没有问题

**Comment by iamcco** [comment]
OK 改成 `>/dev/null 2>&1 &` 了
