### ISSUE TITLE
换行预览bug

### ISSUE THREAD

**Issue by 3xp10it** [iamcco/markdown-preview.vim#54]
在markdown中一个换行符不应该换行,在`markdown-preview.vim`插件中,测试发现一个换行符在预览时会被渲染成真的换行,这与markdown语法有冲突,具体如下:

eg:
=============下面的内容是markdown正文===============

1.bundle的概念来源于NeXTSTEP,它不是一个文件,而是一个按某种标准结构来组织的目录,其中包含了二进制文件及运行所需的资222
源.正向开发中常见的App和framework都是以bundle的形式存在的;framework也是bundle,但framework的bundle中存放的是一个222
dylib,而不是可执行文件.相对来说,framework的地位比App更高,因为一个App的绝大多数功能都是通过调用framework提供的接口222
来实现的.将某个bundle确立为逆向目标后,绝大多数逆向线索都可以在bundle内找到,这大大降低了逆向工程的复杂度

2.Xcode自带的plutil工具可查看plist文件,命令为`plutil -p xxx.plist`

=============上面的内容是markdown正文===============

在上面的markdown内容中,用`markdown-preview.vim`预览时,上面的`222`的位置会真的换行,实际上在markdown语法中,这里是不会换行的,markdown的换行需要2个空格+换行符,在markdown语法中一个换行符在渲染后只会变成一个空格符,也即真实的markdown渲染成html后应该是下面这个样子:

===========真实效果===========
1.bundle的概念来源于NeXTSTEP,它不是一个文件,而是一个按某种标准结构来组织的目录,其中包含了二进制文件及运行所需的资222 源.正向开发中常见的App和framework都是以bundle的形式存在的;framework也是bundle,但framework的bundle中存放的是一个222 dylib,而不是可执行文件.相对来说,framework的地位比App更高,因为一个App的绝大多数功能都是通过调用framework提供的接口222 来实现的.将某个bundle确立为逆向目标后,绝大多数逆向线索都可以在bundle内找到,这大大降低了逆向工程的复杂度
===========真实效果===========

而预览效果是下面这样的:

===========预览效果===========
1.bundle的概念来源于NeXTSTEP,它不是一个文件,而是一个按某种标准结构来组织的目录,其中包含了二进制文件及运行所需的资222
源.正向开发中常见的App和framework都是以bundle的形式存在的;framework也是bundle,但framework的bundle中存放的是一个222
dylib,而不是可执行文件.相对来说,framework的地位比App更高,因为一个App的绝大多数功能都是通过调用framework提供的接口222
来实现的.将某个bundle确立为逆向目标后,绝大多数逆向线索都可以在bundle内找到,这大大降低了逆向工程的复杂度
===========预览效果===========

**Comment by dangoron** [comment]
环境：archlinux
浏览器：firefox58
同样有以上问题。
句末换行会被渲染成一个独立的<p>...</p>块。

**Comment by iamcco** [comment]
fix.
