### ISSUE TITLE
Please add the `g:instant_markdown_open_to_the_world` Option

### ISSUE THREAD

**Issue by bwangelme** [iamcco/markdown-preview.vim#61]
Hello, iamcco, thanks for your plugin, it helps me a lot. 

Can you add a option `g:instant_markdown_open_to_the_world` like the [suan/vim-instant-markdown](https://github.com/suan/vim-instant-markdown#ginstant_markdown_open_to_the_world). If I enable this option, the server will listen on the `0.0.0.0`, in this case, my colleague can also see what I wrote.

**Comment by iamcco** [comment]
add `g:mkdp_open_to_the_world` option.

see https://github.com/iamcco/markdown-preview.vim/blob/master/doc/mkdp.txt#L58

**Comment by bwangelme** [comment]
@iamcco thanks a lot.
