### ISSUE TITLE
The proxy cause the connection problem

### ISSUE THREAD

**Issue by cposture** [iamcco/markdown-preview.vim#7]
I configure the web borwser proxy to a proxy URL(by default the connection setting is No proxy),but occur a connection problem when start the markdown-preview.

How to solve the problem when I configure the web borwser proxy to a proxy URL?
Thanks in advance!

**Comment by iamcco** [comment]
@cposture maybe you can set to bypass proxy server for the local address of `127.0.0.1`

**Comment by iamcco** [comment]
Closed!
