### ISSUE TITLE
spacevim中出现E492：Not an editor command：MarkdownPreview

### ISSUE THREAD

**Issue by michelfei** [iamcco/markdown-preview.vim#71]
win10 下的gvim，用的spacevim配置，python试过可以支持，打开文件后输入：MarkdownPreview会出现如题的E492错误。
配置我写在了.spacevim文件夹下的vimrc中。
能帮忙看一下可能是哪里有问题吗？

**Comment by iamcco** [comment]
这个是因为插件没安装成功，你看下spacevim是怎么安装插件的
