### ISSUE TITLE
無法顯示內容

### ISSUE THREAD

**Issue by misakisuna705** [iamcco/markdown-preview.vim#74]
你好
我最近用vim打開md檔
自動開啟網頁時，md檔的內容都無法顯示
而且關掉時，網頁也不會自動關閉
(上週都正常)

設定只有這三行
Plug 'iamcco/markdown-preview.vim', {'for': ['markdown']}
let g:mkdp_auto_start = 1
Plug 'iamcco/mathjax-support-for-mkdp', {'for': ['markdown']}

**Comment by misakisuna705** [comment]
目前發現都要手動MarkdownPreviewStop再MarkdownPreviewh才會正常運作
下次進入又有問題@@

**Comment by newdee** [comment]
我也有这个问题

**Comment by iamcco** [comment]
> 目前發現都要手動MarkdownPreviewStop再MarkdownPreview才會正常運作
> 下次進入又有問題@@
> 
> 感覺是
> let g:mkdp_auto_start = 1
> 的問題

这个问题我更新了一下，你更新下插件看下这个问题解决没

> 你好
> 我最近用vim打開md檔
> 自動開啟網頁時，md檔的內容都無法顯示
> 而且關掉時，網頁也不會自動關閉
> (上週都正常)
> 
> 設定只有這三行
> Plug 'iamcco/markdown-preview.vim', {'for': ['markdown']}
> let g:mkdp_auto_start = 1
> Plug 'iamcco/mathjax-support-for-mkdp', {'for': ['markdown']}

这个问题更新后看下还存在吗

**Comment by misakisuna705** [comment]
我剛剛更新了，還是不行喔

**Comment by iamcco** [comment]
@misakisuna705 

请列一下

使用的系统：
vim/neovim 版本：
python 版本：

或者到插件目录 `git reset c09a1cad5da33602344027367a57814d0c283078 && git checkout -- .` reset 到这个commit 测下有没有问题，上周应该是在这个commit

**Comment by misakisuna705** [comment]
好的

系統 MacOS 10.13.6 ( High Sierra )
vim 8.1.450
pyhton 3.7.0

我詳細說明一下狀況

當設置 let g:mkdp_auto_start = 1 時
在終端輸入 vim xxx.md 會自動在瀏覽器 ( safari ) 開啟新分頁，但是沒有顯示內容

這時在 vim 中輸入 :MarkdownPreviewStop，再輸入 :MarkdownPreview
會再開啟一個新分頁，能正常顯示內容
而且關閉 vim 時，也會自動關閉該分頁
然而第一個沒顯示內容的分頁還在那裡

下一次一樣在終端輸入 vim xxx.md 時，又會開啟一個沒顯示內容的分頁

**Comment by misakisuna705** [comment]
我輸入  git reset c09a1cad5da33602344027367a57814d0c283078 && git checkout -- .
顯示      fatal: Could not parse object 'c09a1cad5da33602344027367a57814d0c283078'.

**Comment by iamcco** [comment]
更新下插件，这个问题是因为 bufenter 的时候打开预览，没有触发 cursorhold 事件，所以vim这边没有push内容到预览这边，现在增加了异步异步主动push的操作。

`let g:mkdp_delay_start_browser = 800` 这是默认值，试下打开预览有没有内容，如果还是没有，试着增加这个时间

**Comment by misakisuna705** [comment]
都試過了，還是不行喔
只有載入時，稍微延遲而已，內容還是沒有進來

**Comment by iamcco** [comment]
再更新一下，试下，把延迟打开浏览和起延迟自动refresh分开了。

如果还不行，`let g:mkdp_delay_auto_refresh = 3000` 设置为3秒试下，延迟3秒这个理论肯定是可以的

**Comment by misakisuna705** [comment]
還是不行喔
下面三行我都有設定
let g:mkdp_auto_start = 1
let g:mkdp_delay_start_browser = 800
let g:mkdp_delay_auto_refresh = 3000

它只是慢一點跳出分頁而已
還是沒有內容

不知道能不能讓vim一進去就跑 :MarkdownPreview
因為這個指令是正常的

**Comment by iamcco** [comment]
@misakisuna705 打开预览页面等了3秒也没有内容？

我的环境和你基本一致，没发现问题：
```
macos
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct  3 2018 05:42:35)
python3: 3.7.0
```
理论上出现这个页面，按你设置的时间，3秒左右就会出现内容：
![image](https://user-images.githubusercontent.com/5492542/46789489-1e680e80-cd6f-11e8-8eda-9b96c5673516.png)

或者这个时候你在vim里面上下移动光标会刷新出来内容么，如果还是没出来可能就是其他问题了

**Comment by iamcco** [comment]
@newdee 这个感觉是服务没起来然后又起了服务，导致vim很卡，我看下能不能修改下这块

**Comment by iamcco** [comment]
@anson2416 打开预览页面，是空白这个是因为vim发送markdown内容的时候，服务还没起来，这个时候，如果操作vim是会更新预览的，这个是插件当初实现上的问题。可以试着修改增加

```viml
let g:mkdp_delay_start_browser
let g:mkdp_delay_auto_refresh
```
这两个配置的时间。

如果使用 neovim 的话可以试下 https://github.com/iamcco/markdown-preview.nvim 这个插件，这个插件使用了 neovim 的 rpc api，所以在实现上没有这个问题

**Comment by iamcco** [comment]
@lan542662 能打开浏览器设置就是对的

**Comment by marsjane** [comment]
> @marsjane 试着增加 `g:mkdp_delay_auto_refresh` 的时间

ok可以了，感觉因为在虚拟机中运行，浏览器启动比较慢的原因，设置为3000就可以了，many thx！

**Comment by iamcco** [comment]
更新试下还有没有问题
