### ISSUE TITLE
打开Markdown 预览页面后无内容，且Vim变得非常卡

### ISSUE THREAD

**Issue by newdee** [iamcco/markdown-preview.vim#75]
你好，我在按照Readme中安装好插件后，编辑
MD文件时，跳出的是空白页面，而且之后Vim编辑会变得非常卡。
我是使用Vundle安装的。vim手动编译，支持python

**Comment by HuaiYu-Chao** [comment]
我遇過
你是否同時有安裝py2和py3

**Comment by newdee** [comment]
> 我遇過
> 你是否同時有安裝py2和py3

对的，都装了，有问题吗？

**Comment by HuaiYu-Chao** [comment]
不知道怎麼標記

我把其中一個版本刪掉後就正常了的樣子
忘記是刪哪個  你可能要試一下

但我沒看過源碼  不知道問題出在哪

**Comment by newdee** [comment]
> 不知道怎麼標記
> 
> 我把其中一個版本刪掉後就正常了的樣子
> 忘記是刪哪個 你可能要試一下
> 
> 但我沒看過源碼 不知道問題出在哪

python2是肯定不能卸载的，用的是Ubuntu16，卸载了python2系统都会出问题，卸载python3也会有问题，默认的gnome程序都没了

**Comment by HuaiYu-Chao** [comment]
或者重編譯只支持一個版本python的vim應該也可以

如果其他插件剛好有吃py2跟py3的話那我也幫不上忙了  只能請作者

**Comment by newdee** [comment]
不行，刚刚卸载了python3，系统都崩了，还好及时修复。以后别随便叫人卸载python了.我重新编译已经解决了，主要问题是按照网上那个教程编译vim，没仔细看，发现里面写的错的，恩，就是这个[简书](https://www.jianshu.com/p/aac78ff576c5)
里面参数是这样的
```
cd vim/src
make clean
./configure --with-features=huge --enable-python3interp --enable-pythoninterp --with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu/ --enable-rubyinterp --enable-luainterp --enable-perlinterp --with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu/ --enable-multibyte --enable-cscope      --prefix=/usr/local/vim/
sudo make install
```

里面写了支持python3确没有写python3的目录，还把python2的目录写了两遍，害得我浪费了一下午时间找问题。。。。

**Comment by newdee** [comment]
不过还是有个问题，就是直接输入预览命令可以正常显示，但是使用快捷键F8，出来的页面都是空白的

**Comment by newdee** [comment]
不行，之前markdownpreview那个命令还可以打开的，现在打开都是空白的了

**Comment by iamcco** [comment]
@newdee 这个插件的相关配置是是什么？贴出来看一下

**Comment by iamcco** [comment]
更新插件试下，应该没有这问题了
