### ISSUE TITLE
预览时chrome未收到数据

### ISSUE THREAD

**Issue by chinuno-usami** [iamcco/markdown-preview.vim#8]
用的windows上64位的vim7.3
有64位python2，已经添加path可以在cmd中输入python直接打开交互解释器了
`echo has(“python”)`输出1，是支持python的

在使用插件预览的时候能够打开chrome，但是显示
>未收到数据

>ERR_EMPTY_RESPONSE
>服务器未发送任何数据，因此无法加载该网页。

vim中提示`server start failed`
手动运行`python server.py`可以在8686看到空白的渲染后的内容（；´д｀）ゞ

**Comment by iamcco** [comment]
@chinuno-usami 信息太少，我也不知道哪里出问题，不过我没有在vim7.3下面测试过

**Comment by iamcco** [comment]
先关了，有问题再打开
