### ISSUE TITLE
无法在 wsl 下打开预览

### ISSUE THREAD

**Issue by LittleClown** [iamcco/markdown-preview.vim#80]
hey，
# 问题
在 wsl 终端下， vim 下无法通过 F8 打开预览（按下后没有任何反应，尝试过重新进入终端，以及直接在 vim 下输入 `:MarkdownPreviewStop` 和 `:MarkdownPreview`，仍然无用），并且没有得到任何报错信息

# 环境
* 我在 wsl 下通过 `/mnt/c/Windows/System32/cmd.exe /c start chrome` 可以打开浏览器，也在 `/etc/profile` 下将这条命令 alias 为 `start-chrome`（可以在 wsl 终端打开浏览器）；
然后在我的 `~/.vimrc` 下添加了如下配置：
```vimrc
  let g:mkdp_command_for_global = 1
  let g:mkdp_path_to_chrome = 'start-chrome' 
  " keymaps
  nnoremap <silent> <F8> <Plug>MarkdownPreview        " for normal mode
  inoremap <silent> <F8> <Plug>MarkdownPreview        " for insert mode
  nnoremap <silent> <F9> <Plug>StopMarkdownPreview    " for normal mode
  inoremap <silent> <F9> <Plug>StopMarkdownPreview    " for insert mode
```
* vim 版本是 8.1；
* echo g:mkdp_server_started = 1；
* echo has('python') = 0
* echo has('python3') = 1

期待你的回复，感谢！

**Comment by iamcco** [comment]
我没有在wsl下测试过，不过从描述来看，应该没有正确打开浏览器。

可以测下下面的方法能不能打开浏览器：

在 vim 里面：

```
:execute '!start-chrome'
```
或
```
:execute '!/mnt/c/Windows/System32/cmd.exe /c start chrome'
```

**Comment by LittleClown** [comment]
hey，感谢你的回复！
> ```
> :execute '!/mnt/c/Windows/System32/cmd.exe /c start chrome'
> ```
这个起作用了！我在 .vimrc 下设置了：` let g:mkdp_path_to_chrome = '/mnt/c/Windows/System32/cmd.exe /c start chrome'`，然后在 vim 下输入 `:MarkdownPreview`，确实在浏览器中成功打开了，mathjax 也能正常工作，很酷！
不过快捷键看起来仍然不起作用，你有什么头绪吗？

**Comment by iamcco** [comment]
试试：

```viml
:nnoremap <F8> :echo 'F8 works'<CR>
```
然后按 f8 看看有输出没，如果没有输出可能是系统或终端占用了该按键

**Comment by LittleClown** [comment]
按 f8 确实没有输出，试了下，f5 和 f6 能看到输出，但是在 `~/.vimrc` 中重新设置为 `F5` 或 `F6` 仍然不起作用。emmm，还是直接 `:MarkdownPreview` 吧，也不是很费事。
再次感谢提供这么好的插件！

**Comment by LittleClown** [comment]
orz，我改成 `nmap <silent> <F6> <Plug>MarkdownPreview` 就能正常起作用了！
