### ISSUE TITLE
无效的表达式: > mkdp#markdownRefresh()})

### ISSUE THREAD

**Issue by zhonghuabao1** [iamcco/markdown-preview.vim#81]
Ubuntu 16系统、VIM-7.4，出现这个错误：

处理 function <SNR>41_serverStart[10]..mkdp#browserStart[2]..<SNR>69_browserStart 时发生错误:
第   29 行:
E15: 无效的表达式: > mkdp#markdownRefresh()})
E116: Invalid arguments for function timer_start

**Comment by iamcco** [comment]
fix, please update and have a try

commit: https://github.com/iamcco/markdown-preview.vim/commit/fced5cac69f2aa9fbad8245d3fb5056449a8ee06

**Comment by zhonghuabao1** [comment]
another error: `E492: 不是编辑器命令：StopMarkdownPreview`

**Comment by bat9r** [comment]
@zhonghuabao1 
If you have time, could you please try edits provided in the pull request and give feedback on how it works in your case. That's will help provide better edits.

**Comment by iamcco** [comment]
@zhonghuabao1 please update and have a try. @bat9r 's PR have fix the problem

**Comment by zhonghuabao1** [comment]
@iamcco @bat9r 
cool, it works well now!
I make a mistake before: I run `:PluginInstall!` to update code, but does not update correctly!

**Comment by zhonghuabao1** [comment]
@iamcco After update my vim version to 8.1, get another bug: [issue84](https://github.com/iamcco/markdown-preview.vim/issues/84)
