### ISSUE TITLE
【Manjaro和WSL】网页显示为空，无法预览

### ISSUE THREAD

**Issue by Karmenzind** [iamcco/markdown-preview.vim#83]
之前偶尔出现这个情况，今天一直不行了，已经更新为最新版本
在Manjaro和archlinux-wsl（映射的Win10的chrome.exe地址）两个环境上，浏览器页面都可以跳出来，但是页面内容为空，刷新、重试（Stop命令之后再Preview）都没用
配置在这里 https://github.com/Karmenzind/dotfiles-and-scripts/blob/master/home_k/.vimrc#L590

**Comment by Karmenzind** [comment]
额，这会儿又能用了……

**Comment by iamcco** [comment]
如果打开页面空白，在vim里面动一下光标页面就有内容的话可以试着增加

`g:mkdp_delay_auto_refresh` 的时间， 比如 试着增加 1000，2000，3000等。

这个打开空白是因为vim推送数据的时候，服务还没起来，所以打开是空白

**Comment by Karmenzind** [comment]
> 如果打开页面空白，在vim里面动一下光标页面就有内容的话

动光标、编辑、保存都没用，必须`刷新、重试（Stop命令之后再Preview）`或重新打开Vim几次才可能生效

今天又出现了，已经尝试`g:mkdp_delay_auto_refresh`1000 2000 3000，都不行

**Comment by iamcco** [comment]
设置下 updatetime 为 3000 试一下，或者把 这一句 https://github.com/iamcco/markdown-preview.vim/blob/master/autoload/mkdp.vim#L73 注释掉看看有没有问题

**Comment by iamcco** [comment]
重新更新试下吧

**Comment by Karmenzind** [comment]
两个环境都可以了，谢谢:thumbsup:

**Comment by roachsinai** [comment]
emm, 发现代码是已经注释掉的。然后设置为1500+可以1000不行，1500也没有明显的停顿感。

**Comment by iamcco** [comment]
@roachsinai

设置的是 updatetime 还是 g:mkdp_delay_auto_refresh ?  推荐的是设置 g:mkdp_delay_auto_refresh

**Comment by roachsinai** [comment]
`g:mkdp_delay_auto_refresh`。
