### ISSUE TITLE
插入本地图片不能显示

### ISSUE THREAD

**Issue by 839891627** [iamcco/markdown-preview.vim#9]
网络图片可以显示，本地目录的就可以。

markdownPad2也是可以正确显示 本地图片链接的.

![qq 20160114170443](https://cloud.githubusercontent.com/assets/10300651/12319985/d5cab450-bae0-11e5-8e78-0c2234910918.png)

**Comment by iamcco** [comment]
@839891627 近段时间添加显示本地图片功能

**Comment by 839891627** [comment]
@iamcco 期待~ 这个插件真好用的~

**Comment by iamcco** [comment]
@839891627 更新了，增加显示本地图片

**Comment by Zxrcoming** [comment]
图片无法显示了

**Comment by Zxrcoming** [comment]
图片无法显示了 ，这是网上的照片

![image](http://67.205.139.234/images/841092_1563443589.png)

**Comment by iamcco** [comment]
@Zxrcoming 换这个插件 https://github.com/iamcco/markdown-preview.nvim

**Comment by Zxrcoming** [comment]
这个插件莫名用不了

**Comment by Zxrcoming** [comment]
```bash
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 13 2019 18:58:23)
```
@iamcco

**Comment by Zxrcoming** [comment]
换了　升级了插件就能用　
但是图片还是无法显示 @iamcco

**Comment by iamcco** [comment]
@Zxrcoming 用的哪个插件？怎么插入的图片？

**Comment by Zxrcoming** [comment]
@iamcco 　插件是:
```vim
   Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app & yarn install'  }
```
照片插入形式是：
```vim
   ![my-vimconf](https://github.com/Zxrcoming/vimconf/blob/master/2019-07-18-1563435902_screenshot_1920x1080.jpg)
```

**Comment by Zxrcoming** [comment]
@iamcco   找到原因了
图片链接不对．
感谢回答

**Comment by shizhongzzf** [comment]
> @iamcco 找到原因了
> 图片链接不对．
> 感谢回答

请问本地图片插入可以看了吗？我的还不可以哎

**Comment by iamcco** [comment]
@shizhongzzf 换这个插件 https://github.com/iamcco/markdown-preview.nvim
