### ISSUE TITLE
预览后无显示

### ISSUE THREAD

**Issue by Loutine** [iamcco/markdown-preview.vim#90]
系统：win10
版本：vim8.1源码重编译，支持py27与py36
问题：
按照之前的issue多次尝试后 更改refresh 和updatetime 为1000 1500 2000 3000仍无明显效果
网页结果仍然为空白状态。
![image](https://user-images.githubusercontent.com/33801505/58114528-7da5cf80-7c2a-11e9-9063-07b333c095d6.png)

**Comment by iamcco** [comment]
设置  `g:mkdp_delay_auto_refresh` 为 3000 试试

现在话推荐 https://github.com/iamcco/markdown-preview.nvim 这个插件

**Comment by Loutine** [comment]
没有明显的效果 哭哭惹T^T
![image](https://user-images.githubusercontent.com/33801505/58163326-67ddec00-7cb6-11e9-9537-c1690b90673b.png)
这是我的配置信息。刚才试用了新插件效果相当好
就是有点不甘心。。。重新编译后的东西不知道为什么不支持。。。会不会是py版本或者编码的问题

**Comment by Loutine** [comment]
算了有新的好用的了，我就不纠结了
close~

**Comment by Loutine** [comment]
已经解决了~
原因是因为编译的时候使用了32位的py27与vim-64位不匹配不能调用python.dll
感谢大佬耐心
