### ISSUE TITLE
执行MarkdownPreview报错，求解决！！！

### ISSUE THREAD

**Issue by Piller4F** [iamcco/markdown-preview.vim#93]
不知道是什么问题
![QQ截图20191115154652](https://user-images.githubusercontent.com/49083286/68925960-479f6d80-07bf-11ea-87bb-fc7a07a9c0d7.png)

**Comment by iamcco** [comment]
vim 版本太老

**Comment by Piller4F** [comment]
> vim 版本太老

![QQ截图20191115160210](https://user-images.githubusercontent.com/49083286/68926849-63a40e80-07c1-11ea-9e92-0a1ae1e017d9.png)
应该不是版本问题吧

**Comment by Piller4F** [comment]
@iamcco

**Comment by Piller4F** [comment]
我刚看到是大于等于8.1版本，对不起打扰了，谢谢谢谢！！！ @iamcco
